import type { Dictionary } from "./types";

export const en: Dictionary = {
  meta: {
    title: "Wilfer Becerra · AI process automation",
    description:
      "I automate manual work for small businesses with Python, n8n and AI. Founder of Exodus Logistics and Albor Automations, with hands-on experience in last-mile logistics.",
  },
  brand: { home: "Wilfer Becerra, go to home" },
  nav: {
    about: "About",
    projects: "Projects",
    albor: "Albor",
    skills: "Skills",
    experience: "Experience",
    contact: "Contact",
  },
  a11y: {
    skip: "Skip to content",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    language: "Language",
    mainNav: "Main navigation",
    themeLight: "Switch to light theme",
    themeDark: "Switch to dark theme",
  },
  hero: {
    title: "I turn *manual* work into systems that *almost run themselves.*",
    description:
      "Before I wrote code, I delivered parcels, coordinated drivers and kept the books for a delivery company. Now I build the tools I wish I'd had back then, using Python, n8n and Claude.",
    ctaPrimary: "See projects",
    ctaSecondary: "Get in touch",
    scroll: "Scroll",
  },
  about: {
    eyebrow: "About",
    title: "From the warehouse floor to code, *without losing sight* of operations.",
    paragraphs: [
      "I was born in Venezuela and live in Lucena, Spain. Here I've worked in warehousing and last-mile delivery. At Paquetería Lucena I ended up running day-to-day operations and driver payouts, and closing out over 400 parcels a day across apps like GLS, Paack and Tipsa.",
      "That's where I saw the problem up close: notebooks, spreadsheets copied by hand and hours lost every month. I started by digitising it with Excel and PDFs, then automated it with code and AI.",
      "Today I run two projects: Exodus Logistics, software for delivery companies, and Albor Automations, an automation agency for small businesses. My strength is understanding how people actually work before I build anything.",
    ],
    facts: [
      { label: "Based in", value: "Lucena, Spain" },
      { label: "Focus", value: "Automation · AI · Operations" },
      { label: "Languages", value: "Native Spanish · Basic English and Italian" },
    ],
    stats: [
      { value: 400, suffix: "+", label: "parcels closed out per day across delivery apps" },
      { value: 99, suffix: "%", label: "delivery success rate as a driver" },
      { value: 40, prefix: "+", suffix: "%", label: "in incident resolution" },
      { value: 10, label: "people coordinated on one team" },
    ],
  },
  pipeline: {
    eyebrow: "How I solve it",
    title: "From *30 hours* to *2*, step by step.",
    intro: "This is how the system I built for a delivery client works. The data in the animation is sample data.",
    sample: "Sample data",
    steps: [
      { title: "The report arrives by chat", detail: "Each driver sends their end-of-day summary via WhatsApp or Telegram, just like before." },
      { title: "It records itself", detail: "The system reads the message and stores it as structured data. Nobody copies it by hand." },
      { title: "Payouts are calculated", detail: "Deliveries, incidents and expenses are totalled per driver without touching a spreadsheet." },
      { title: "The PDF is ready", detail: "The payout statement is ready to send. It only needs a quick review." },
    ],
    chatTitle: "Reports · Lucena route",
    messages: [
      { from: "Driver A", text: "Route 3 · 86 delivered · 2 incidents", time: "19:42" },
      { from: "Driver B", text: "Route 1 · 91 delivered · 0 incidents", time: "19:55" },
      { from: "Driver C", text: "Route 5 · 78 delivered · 3 incidents", time: "20:08" },
    ],
    tableHead: ["Driver", "Delivered", "Incid.", "Amount"],
    rows: [
      ["A", "86", "2", "€107.50"],
      ["B", "91", "0", "€113.75"],
      ["C", "78", "3", "€97.50"],
    ],
    totalLabel: "Daily total",
    total: "€318.75",
    pdfTitle: "Daily payout",
    pdfMeta: "3 drivers · 255 deliveries",
    pdfReady: "Ready to send",
  },
  projects: {
    eyebrow: "Projects",
    title: "Real work, *real problems.*",
    intro: "Every project started as a manual process that someone was struggling with.",
    viewCase: "View case",
    featured: "Featured",
    back: "Back to projects",
    problem: "The problem",
    solution: "The solution",
    role: "My role",
    stack: "Stack",
    result: "Result",
    visit: "Visit",
    next: "Next project",
  },
  flow: {
    title: "How a report flows",
    steps: [
      { title: "Report", detail: "The driver sends it via WhatsApp or Telegram" },
      { title: "Record", detail: "Stored as structured data in the database" },
      { title: "Calculate", detail: "Payouts and expenses kept up to date" },
      { title: "PDF", detail: "A report ready to send" },
    ],
  },
  albor: {
    eyebrow: "Albor Automations",
    title: "*Tailored* automation for small businesses.",
    description:
      "Albor is my automation agency. It finds the repetitive tasks that eat up hours in a business and replaces them with automated workflows, so that time can go into work that creates value.",
    servicesTitle: "What it does",
    services: [
      { title: "Automated workflows", detail: "Processes connected with n8n and Python across the tools a business already uses." },
      { title: "AI integrations", detail: "Claude and GPT to read documents and extract their data, including scanned PDFs." },
      { title: "Automated reports", detail: "Excel files and PDFs generated automatically from the business's own data." },
    ],
    visit: "Visit albor-automations.com",
  },
  skills: {
    eyebrow: "Skills",
    title: "The tools I *work with.*",
    groups: [
      {
        id: "automation",
        name: "Automation",
        items: [
          { name: "n8n", where: "Albor workflows" },
          { name: "Python", where: "Exodus & PDF to Excel" },
          { name: "Reporting workflows", where: "Exodus Logistics" },
          { name: "PDF generation", where: "Automated payouts" },
          { name: "WhatsApp & Telegram bots", where: "Driver reports" },
        ],
      },
      {
        id: "ai",
        name: "AI",
        items: [
          { name: "Claude API", where: "Exodus Logistics" },
          { name: "Claude Vision", where: "Scanned PDFs" },
          { name: "GPT", where: "Albor Automations" },
          { name: "ElevenLabs", where: "Albor Automations" },
          { name: "LLM integration", where: "Albor Automations" },
        ],
      },
      {
        id: "data",
        name: "Data",
        items: [
          { name: "Advanced Excel", where: "Payroll at Paquetería Lucena" },
          { name: "Databases", where: "Exodus Logistics" },
          { name: "Stock control (Odoo)", where: "Prowen S.L." },
          { name: "Payroll calculations", where: "Paquetería Lucena" },
        ],
      },
      {
        id: "systems",
        name: "Systems",
        items: [
          { name: "PowerShell", where: "Local scripting" },
          { name: "CMD", where: "Local scripting" },
          { name: "Windows", where: "Daily environment" },
          { name: "Linux VPS", where: "Own business" },
          { name: "VS Code", where: "Daily development" },
        ],
      },
      {
        id: "ops",
        name: "Operations",
        items: [
          { name: "Team coordination (up to 10)", where: "Paquetería Lucena" },
          { name: "Checklist-based training", where: "Paquetería Lucena" },
          { name: "Delivery apps & PDAs", where: "GLS, Paack, Tipsa…" },
          { name: "Incident resolution", where: "Paquetería Lucena" },
        ],
      },
    ],
    whereLabel: "Where",
  },
  experience: {
    eyebrow: "Experience",
    title: "An *unusual* path.",
    present: "Present",
    education: "Education",
    items: [
      {
        period: "Jan 2026 — Present",
        role: "Founder",
        company: "Exodus Logistics · Albor Automations",
        summary: "AI process automation for small businesses, with a focus on logistics.",
        highlights: [
          "Built automated reporting, payouts and PDF generation for a parcel delivery company.",
          "The same client has been using the system for over 4 months.",
        ],
      },
      {
        period: "Sep 2025 — Present",
        role: "Warehouse operative",
        company: "Prowen S.L.",
        summary: "Unloading containers, assembling bicycles, picking orders and stock control in Odoo.",
        highlights: ["Picked up to 50 orders of 5+ packages (25 kg each) in under an hour."],
      },
      {
        period: "May 2024 — Aug 2025",
        role: "Operations manager & bookkeeper",
        company: "Paquetería Lucena",
        summary: "Daily operations, driver payouts, parcel close-out across several delivery apps, and deliveries of my own.",
        highlights: [
          "Improved incident resolution and successful deliveries by 40%.",
          "Moved driver payouts from paper notebooks to Excel and PDF.",
          "99% delivery success rate: 80–90 parcels in under 4 hours.",
        ],
      },
    ],
    school: {
      period: "2018 — 2023",
      title: "High school diploma, Science & Technology",
      institution: "Liceo Bolivariano, Venezuela",
      note: "Recognised by teachers as the top student of my year.",
    },
    languagesTitle: "Languages",
    languages: [
      { name: "Spanish", level: "Native" },
      { name: "English", level: "A1" },
      { name: "Italian", level: "A1" },
    ],
  },
  certifications: {
    eyebrow: "Learning",
    title: "Degrees and *certificates.*",
    intro: "Courses and certifications I have completed or am currently taking.",
    inProgress: "In progress",
    view: "View credential",
  },
  approach: {
    eyebrow: "How I work",
    title: "Process first, *code* second.",
    steps: [
      { title: "Understand", detail: "See how the work is done today and where the time goes." },
      { title: "Define", detail: "Decide what to automate and what should stay with a person." },
      { title: "Build", detail: "Build on top of the tools the team already knows." },
      { title: "Validate", detail: "Test it with real data before calling it done." },
      { title: "Improve", detail: "Adjust it as it's used every day and as the client asks for changes." },
    ],
  },
  testimonial: {
    eyebrow: "What clients say",
    client: "Client of",
    pending: "Review pending",
    pendingNote: "Yohan's review, in his own words, will go here.",
    prev: "Previous review",
    next: "Next review",
    goTo: "Go to review",
  },
  contact: {
    eyebrow: "Contact",
    title: "Open to new projects and *job opportunities.*",
    description:
      "AI automation, custom development, or a role in operations and administration. Tell me what you have in mind and I'll reply with an initial assessment and the next steps.",
    email: "Send an email",
    copy: "Copy email",
    copied: "Copied to clipboard",
    gmail: "Open in Gmail",
    mailApp: "Use my mail app",
  },
  footer: { rights: "All rights reserved.", top: "Back to top", sitemap: "Sections", social: "Find me", tagline: "From manual work to automated systems." },
  pendingImage: "Screenshot pending",
};
