import type { Dictionary } from "./types";

export const es: Dictionary = {
  meta: {
    title: "Wilfer Becerra · Automatización de procesos con IA",
    description:
      "Automatizo tareas manuales de pymes con Python, n8n e IA. Fundador de Exodus Logistics y Albor Automations, con experiencia real en logística de última milla.",
  },
  brand: { home: "Wilfer Becerra, ir al inicio" },
  nav: {
    about: "Sobre mí",
    projects: "Proyectos",
    albor: "Albor",
    skills: "Habilidades",
    experience: "Experiencia",
    contact: "Contacto",
  },
  a11y: {
    skip: "Saltar al contenido",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
    language: "Idioma",
    mainNav: "Navegación principal",
    themeLight: "Cambiar a tema claro",
    themeDark: "Cambiar a tema oscuro",
  },
  hero: {
    title: "Convierto el trabajo *manual* en sistemas que se gestionan *casi solos.*",
    description:
      "Antes de programar, repartí paquetes, coordiné repartidores y llevé las cuentas de una empresa de paquetería. Ahora construyo con Python, n8n y Claude las herramientas que me habría gustado tener entonces.",
    ctaPrimary: "Ver proyectos",
    ctaSecondary: "Contactar",
    scroll: "Desliza",
  },
  about: {
    eyebrow: "Sobre mí",
    title: "Del almacén al código, *sin perder de vista* la operativa.",
    paragraphs: [
      "Nací en Venezuela y vivo en Lucena (Córdoba). Aquí he trabajado en almacén y en reparto de última milla. En Paquetería Lucena acabé llevando la operativa diaria, los pagos de los repartidores y el cierre de más de 400 paquetes al día en las apps de GLS, Paack, Tipsa y otras.",
      "Allí vi el problema de cerca: libretas, hojas de cálculo copiadas a mano y horas perdidas cada mes. Empecé a digitalizarlo con Excel y PDF, y después a automatizarlo con código e IA.",
      "Hoy dirijo dos proyectos: Exodus Logistics, un software para empresas de reparto, y Albor Automations, una agencia de automatización para pymes. Mi punto fuerte es entender primero cómo trabaja la gente y construir después.",
    ],
    facts: [
      { label: "Base", value: "Lucena, Córdoba" },
      { label: "Enfoque", value: "Automatización · IA · Operaciones" },
      { label: "Idiomas", value: "Español nativo · Inglés e italiano básico" },
    ],
    stats: [
      { value: 400, suffix: "+", label: "paquetes cerrados al día en las apps de reparto" },
      { value: 99, suffix: "%", label: "de entregas correctas como repartidor" },
      { value: 40, prefix: "+", suffix: "%", label: "en resolución de incidencias" },
      { value: 10, label: "personas coordinadas en un equipo" },
    ],
  },
  pipeline: {
    eyebrow: "Cómo lo resuelvo",
    title: "De *30 horas* a *2*, paso a paso.",
    intro: "Así funciona el sistema que monté para un cliente de paquetería. Los datos de la animación son de ejemplo.",
    sample: "Datos de ejemplo",
    steps: [
      { title: "El reporte llega por chat", detail: "Cada repartidor manda su resumen del día por WhatsApp o Telegram, como ya hacía." },
      { title: "Se registra solo", detail: "El sistema lee el mensaje y lo guarda estructurado en la base de datos. Nadie lo copia a mano." },
      { title: "Se calcula la liquidación", detail: "Entregas, incidencias y gastos se suman por repartidor sin tocar una hoja de cálculo." },
      { title: "Sale el PDF", detail: "La liquidación queda lista para enviar. Solo hace falta revisarla." },
    ],
    chatTitle: "Reportes · Ruta Lucena",
    messages: [
      { from: "Repartidor A", text: "Ruta 3 · 86 entregados · 2 incidencias", time: "19:42" },
      { from: "Repartidor B", text: "Ruta 1 · 91 entregados · 0 incidencias", time: "19:55" },
      { from: "Repartidor C", text: "Ruta 5 · 78 entregados · 3 incidencias", time: "20:08" },
    ],
    tableHead: ["Repartidor", "Entregas", "Incid.", "Importe"],
    rows: [
      ["A", "86", "2", "107,50 €"],
      ["B", "91", "0", "113,75 €"],
      ["C", "78", "3", "97,50 €"],
    ],
    totalLabel: "Total del día",
    total: "318,75 €",
    pdfTitle: "Liquidación diaria",
    pdfMeta: "3 repartidores · 255 entregas",
    pdfReady: "Listo para enviar",
  },
  projects: {
    eyebrow: "Proyectos",
    title: "Trabajo real, con *problemas reales.*",
    intro: "Cada proyecto nace de un proceso manual que alguien estaba sufriendo.",
    viewCase: "Ver caso",
    featured: "Destacado",
    back: "Volver a proyectos",
    problem: "El problema",
    solution: "La solución",
    role: "Mi papel",
    stack: "Tecnología",
    result: "Resultado",
    visit: "Visitar",
    next: "Siguiente proyecto",
  },
  flow: {
    title: "Cómo fluye un reporte",
    steps: [
      { title: "Reporte", detail: "El repartidor escribe por WhatsApp o Telegram" },
      { title: "Registro", detail: "Se guarda estructurado en la base de datos" },
      { title: "Cálculo", detail: "Liquidaciones y gastos al día" },
      { title: "PDF", detail: "Informe listo para enviar" },
    ],
  },
  albor: {
    eyebrow: "Albor Automations",
    title: "Automatización *a medida* para pymes.",
    description:
      "Albor es mi agencia de automatización. Busca las tareas repetitivas que consumen horas en un negocio y las sustituye por flujos automáticos, para que ese tiempo se dedique a lo que genera valor.",
    servicesTitle: "Qué hace",
    services: [
      { title: "Flujos automáticos", detail: "Procesos conectados con n8n y Python entre las herramientas que ya usa el negocio." },
      { title: "Integraciones con IA", detail: "Claude y GPT para leer documentos y extraer sus datos, también de PDFs escaneados." },
      { title: "Informes automáticos", detail: "Excel y PDFs que se generan solos a partir de los datos del negocio." },
    ],
    visit: "Visitar albor-automations.com",
  },
  skills: {
    eyebrow: "Habilidades",
    title: "Herramientas con las que *trabajo.*",
    groups: [
      {
        id: "automation",
        name: "Automatización",
        items: [
          { name: "n8n", where: "Flujos de Albor" },
          { name: "Python", where: "Exodus y PDF to Excel" },
          { name: "Flujos de reportes", where: "Exodus Logistics" },
          { name: "Generación de PDFs", where: "Liquidaciones automáticas" },
          { name: "Bots de WhatsApp y Telegram", where: "Reportes de repartidores" },
        ],
      },
      {
        id: "ai",
        name: "IA",
        items: [
          { name: "Claude API", where: "Exodus Logistics" },
          { name: "Claude Vision", where: "PDFs escaneados" },
          { name: "GPT", where: "Albor Automations" },
          { name: "ElevenLabs", where: "Albor Automations" },
          { name: "Integración de LLMs", where: "Albor Automations" },
        ],
      },
      {
        id: "data",
        name: "Datos",
        items: [
          { name: "Excel avanzado", where: "Pagos en Paquetería Lucena" },
          { name: "Bases de datos", where: "Exodus Logistics" },
          { name: "Control de stock (Odoo)", where: "Prowen S.L." },
          { name: "Contabilidad de pagos", where: "Paquetería Lucena" },
        ],
      },
      {
        id: "systems",
        name: "Sistemas",
        items: [
          { name: "PowerShell", where: "Scripts y tareas locales" },
          { name: "CMD", where: "Scripts y tareas locales" },
          { name: "Windows", where: "Entorno de trabajo diario" },
          { name: "VPS Linux", where: "Emprendimiento propio" },
          { name: "VS Code", where: "Desarrollo diario" },
        ],
      },
      {
        id: "ops",
        name: "Operaciones",
        items: [
          { name: "Coordinación de equipos (hasta 10)", where: "Paquetería Lucena" },
          { name: "Formación con checklists", where: "Paquetería Lucena" },
          { name: "Apps de reparto y PDAs", where: "GLS, Paack, Tipsa…" },
          { name: "Resolución de incidencias", where: "Paquetería Lucena" },
        ],
      },
    ],
    whereLabel: "Dónde",
  },
  experience: {
    eyebrow: "Experiencia",
    title: "Una trayectoria *poco habitual.*",
    present: "Actualidad",
    education: "Formación",
    items: [
      {
        period: "Ene 2026 — Actualidad",
        role: "Fundador",
        company: "Exodus Logistics · Albor Automations",
        summary: "Automatización de procesos con IA para pymes, especialmente del sector logístico.",
        highlights: [
          "Sistema de reportes, liquidaciones y PDFs automáticos para una empresa de paquetería.",
          "El mismo cliente sigue usando el sistema tras más de 4 meses.",
        ],
      },
      {
        period: "Sep 2025 — Actualidad",
        role: "Mozo de almacén",
        company: "Prowen S.L.",
        summary: "Descarga de contenedores, montaje de bicicletas, preparación de pedidos y control de stock con Odoo.",
        highlights: ["Hasta 50 pedidos de más de 5 bultos de 25 kg preparados en menos de una hora."],
      },
      {
        period: "May 2024 — Ago 2025",
        role: "Encargado, contable y gestor de operaciones",
        company: "Paquetería Lucena",
        summary: "Operativa diaria, pagos a repartidores, cierre de paquetes en varias apps de reparto y reparto propio.",
        highlights: [
          "+40% en la resolución de incidencias y entregas.",
          "Pagos a repartidores digitalizados: de libretas a Excel y PDF.",
          "99% de entregas correctas: 80-90 paquetes en menos de 4 horas.",
        ],
      },
    ],
    school: {
      period: "2018 — 2023",
      title: "Bachiller en Ciencias y Tecnología",
      institution: "Liceo Bolivariano, Venezuela",
      note: "Reconocido por el profesorado como mejor alumno de su promoción.",
    },
    languagesTitle: "Idiomas",
    languages: [
      { name: "Español", level: "Nativo" },
      { name: "Inglés", level: "A1" },
      { name: "Italiano", level: "A1" },
    ],
  },
  certifications: {
    eyebrow: "Formación",
    title: "Títulos y *certificados.*",
    intro: "Cursos y certificaciones que he completado o estoy cursando.",
    inProgress: "En curso",
    view: "Ver credencial",
  },
  approach: {
    eyebrow: "Cómo trabajo",
    title: "Primero el proceso, *después* el código.",
    steps: [
      { title: "Entender", detail: "Ver cómo se hace hoy el trabajo y dónde se pierde el tiempo." },
      { title: "Definir", detail: "Decidir qué se automatiza y qué conviene dejar en manos de una persona." },
      { title: "Construir", detail: "Montar la solución sobre las herramientas que el equipo ya conoce." },
      { title: "Validar", detail: "Probarla con datos reales antes de darla por buena." },
      { title: "Mejorar", detail: "Ajustarla con el uso diario y lo que pide el cliente." },
    ],
  },
  testimonial: {
    eyebrow: "Lo que dicen",
    client: "Cliente de",
    pending: "Reseña pendiente",
    pendingNote: "Aquí irá la opinión de Yohan con sus propias palabras.",
    prev: "Reseña anterior",
    next: "Reseña siguiente",
    goTo: "Ir a la reseña",
  },
  contact: {
    eyebrow: "Contacto",
    title: "Abierto a nuevos proyectos y *propuestas de trabajo.*",
    description:
      "Automatización con IA, desarrollo a medida o un puesto en operaciones y administración. Escríbeme con lo que tienes en mente y te respondo con un primer análisis y los siguientes pasos.",
    email: "Escribir un email",
    copy: "Copiar email",
    copied: "Copiado al portapapeles",
    gmail: "Abrir en Gmail",
    mailApp: "Usar mi app de correo",
  },
  footer: { rights: "Todos los derechos reservados.", top: "Volver arriba", sitemap: "Secciones", social: "Encuéntrame", tagline: "Del trabajo manual al sistema automático." },
  pendingImage: "Captura pendiente",
};
