import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "exodus-logistics",
    title: "Exodus Logistics",
    featured: true,
    kicker: { es: "Plataforma de gestión para reparto de última milla", en: "Operations platform for last-mile delivery" },
    summary: {
      es: "Reportes, liquidaciones y facturación de empresas de reparto, automatizados de principio a fin. Funciona hoy como un bot de WhatsApp para un cliente, y la versión web para varias empresas está en desarrollo.",
      en: "Reports, driver payouts and invoicing for delivery companies, automated end to end. It runs today as a WhatsApp bot for one client, and a multi-company web version is in development.",
    },
    role: { es: "Fundador. Diseño, desarrollo y soporte", en: "Founder. Design, development and support" },
    period: { es: "2026 — actualidad", en: "2026 — present" },
    problem: {
      es: "En una empresa de paquetería, los reportes diarios de cada repartidor se apuntaban a mano y a fin de mes había que cruzarlos en Excel para calcular pagos. Eran unas 30 horas al mes de trabajo manual, con errores que se traducían en dinero.",
      en: "At a parcel delivery company, each driver's daily report was written down by hand and reconciled in Excel at month end to calculate pay. That meant around 30 hours of manual work every month, and mistakes that cost real money.",
    },
    solution: {
      es: [
        "Los repartidores envían su reporte por WhatsApp o Telegram y el sistema lo registra directamente en una base de datos.",
        "Las liquidaciones y los informes se generan automáticamente en PDF, sin volver a teclear datos.",
        "En desarrollo: una versión web para que varias empresas usen la plataforma, cada una con sus propios datos.",
      ],
      en: [
        "Drivers send their report via WhatsApp or Telegram and the system stores it straight into a database.",
        "Payouts and reports are generated automatically as PDFs, with no data re-entry.",
        "In development: a web version so several companies can use the platform, each with its own isolated data.",
      ],
    },
    result: {
      value: "30 h → 2 h",
      label: { es: "al mes de gestión, que ahora solo requiere supervisión", en: "per month of admin work, now reduced to supervision" },
    },
    technologies: ["Python", "Claude API", "WhatsApp", "Telegram", "Database", "PDF", "VPS Linux"],
    images: [
      {
        src: "/capturas/exodus-bot.webp",
        alt: { es: "Repartidores enviando sus reportes al bot de WhatsApp", en: "Drivers sending their reports to the WhatsApp bot" },
        pending: { es: "Mensajes de reportes por WhatsApp", en: "WhatsApp report messages" },
      },
      {
        src: "/capturas/exodus-pdf.webp",
        alt: { es: "Cierre mensual en PDF generado por el sistema (nombres anonimizados)", en: "Monthly payout PDF generated by the system (names anonymised)" },
        pending: { es: "PDF de liquidación generado (anonimizado)", en: "Generated payout PDF (anonymised)" },
      },
    ],
    // Pendiente: confirmar el dominio antes de activarlo.
    liveUrl: undefined,
  },
  {
    slug: "pdf-to-excel",
    title: "PDF to Excel",
    kicker: { es: "Extracción masiva de facturas", en: "Bulk invoice extraction" },
    summary: {
      es: "Convierte cientos de facturas en PDF en un único Excel ordenado y verificado. Si el PDF es escaneado, lo lee con Claude Vision.",
      en: "Turns hundreds of PDF invoices into a single, organised and validated Excel file. Scanned PDFs are read with Claude Vision.",
    },
    role: { es: "Desarrollo completo", en: "Sole developer" },
    problem: {
      es: "Las facturas llegan como PDFs sueltos, unos con texto y otros escaneados. Pasarlas a mano a una hoja de cálculo es lento y propenso a errores.",
      en: "Invoices arrive as loose PDFs, some with text and some scanned. Typing them into a spreadsheet by hand is slow and error-prone.",
    },
    solution: {
      es: [
        "Si el PDF tiene texto, se extrae directamente.",
        "Si es escaneado, se envía a Claude Vision para reconocer los datos.",
        "Todo se vuelca en un solo Excel con fórmulas y comprobaciones, agrupado por categoría.",
      ],
      en: [
        "Text-based PDFs are parsed directly.",
        "Scanned PDFs are sent to Claude Vision to recognise the data.",
        "Everything lands in a single Excel file with formulas and checks, grouped by category.",
      ],
    },
    result: {
      value: "500",
      label: { es: "PDFs procesados en una sola ejecución", en: "PDFs processed in a single run" },
    },
    technologies: ["Python", "Claude Vision", "Excel", "PDF"],
    images: [
      {
        src: "/capturas/pdf-excel-resumen.webp",
        alt: { es: "Excel resultante: resumen general con tablas y gráficos (nombres difuminados)", en: "Resulting Excel: general summary with tables and charts (names blurred)" },
        pending: { es: "Después: Excel resultante", en: "After: resulting Excel" },
      },
      {
        src: "/capturas/pdf-excel-menu.webp",
        alt: { es: "Menú de la herramienta en la terminal: periodos procesados y opciones", en: "The tool's terminal menu: processed periods and options" },
        pending: { es: "Menú de la herramienta", en: "Tool menu" },
      },
      {
        src: "/capturas/pdf-excel-antes.webp",
        alt: { es: "Antes: carpeta con los PDFs de origen", en: "Before: folder with the source PDFs" },
        pending: { es: "Antes: carpeta con los PDFs", en: "Before: folder of PDFs" },
      },
    ],
  },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
